//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palashicheva_402_ProkatCars.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int IdFeedback { get; set; }
        public string Sender { get; set; }
        public string Text { get; set; }
        public int StarId { get; set; }
    
        public virtual Star Star { get; set; }
    }
}
